global:
  state_dir: "./state"
  temp_dir: "./tmp"
  log_level: "INFO"
  timeout: 60
  user_agent: "romvault-dat-updater/2.0"
  cleanup_before_extract: false

sources:
  - name: NoIntro-Snes
    enabled: true
    url: "https://datomatic.no-intro.org/index.php?page=download&op=dat&s=193"
    output_dir: "/romvault/DatRoot/No-Intro/SNES"
    cleanup_before_extract: true

  - name: NoIntro-Nes
    enabled: true
    url: "https://datomatic.no-intro.org/index.php?page=download&op=dat&s=165"
    output_dir: "/romvault/DatRoot/No-Intro/NES"

  - name: NoIntro-Megadrive
    enabled: true
    url: "https://datomatic.no-intro.org/index.php?page=download&op=dat&s=32"
    output_dir: "/romvault/DatRoot/No-Intro/MegaDrive"

  - name: NoIntro-Spectrum
    enabled: false
    url: "https://datomatic.no-intro.org/index.php?page=download&op=dat&s=48"
    output_dir: "/romvault/DatRoot/No-Intro/Spectrum"
    
  - name: 1G1R-Snes
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/SNES"
    cleanup_before_extract: true
    
  - name: 1G1R-Nes
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/NES"
    
  - name: 1G1R-Megadrive
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Sega%20-%20Mega%20Drive%20-%20Genesis%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/MegaDrive"
    
  - name: 1G1R-32X
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Sega%20-%2032X%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/32X"

  - name: 1G1R-SG1000
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Sega%20-%20SG-1000%20-%20SC-3000%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/SG1000"

  - name: 1G1R-MasterSystem
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Sega%20-%20Master%20System%20-%20Mark%20III%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/SMS"

  - name: 1G1R-GameGear
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Sega%20-%20Game%20Gear%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/GG"

  - name: 1G1R-TurboGrafx
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/NEC%20-%20PC%20Engine%20-%20TurboGrafx-16%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/TurboGrafx"
    
  - name: 1G1R-SuperGrafx
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/NEC%20-%20PC%20Engine%20SuperGrafx%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/SuperGrafx"
    
  - name: 1G1R-GameBoy
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Nintendo%20-%20Game%20Boy%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/GameBoy"
    
  - name: 1G1R-GameBoyColor
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Nintendo%20-%20Game%20Boy%20Color%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/GameBoyColor"
  
  - name: 1G1R-Virtualboy
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Nintendo%20-%20Virtual%20Boy%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Vectrex"
    
  - name: 1G1R-Atari2600
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Atari%20-%20Atari%205200%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Atari5200"

  - name: 1G1R-Atari5200
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Atari%20-%20Atari%207800%20(BIN)%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Atari7800"

  - name: 1G1R-Atari7800
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Atari%20-%20Atari%207800%20(BIN)%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Atari7800"
  
  - name: 1G1R-AtariLynx
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Atari%20-%20Atari%20Lynx%20(LYX)%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/AtariLynx"

  - name: 1G1R-Coleco
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Coleco%20-%20ColecoVision%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Coleco"
    
  - name: 1G1R-ChannelF
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Fairchild%20-%20Channel%20F%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/ChannelF"

  - name: 1G1R-Intellivision
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Mattel%20-%20Intellivision%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Intellivision"

  - name: 1G1R-Vectrex
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/GCE%20-%20Vectrex%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Vectrex"

  - name: 1G1R-VideoPac
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Philips%20-%20Videopac%2B%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/VideoPac"

  - name: 1G1R-WataraSupervision
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/Watara%20-%20Supervision%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/Supervision"


  - name: 1G1R-NeoGeoPocket
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/SNK%20-%20NeoGeo%20Pocket%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/NGP"

  - name: 1G1R-NeoGeoPocketColor
    enabled: true
    url: "https://raw.githubusercontent.com/UnluckyForSome/Fresh1G1R/refs/heads/main/daily-1g1r-dat/McLean/no-intro/SNK%20-%20NeoGeo%20Pocket%20Color%20(No-Intro%20-%20Fresh1G1R%20-%20McLean).dat"
    output_dir: "/romvault/DatRoot/1G1R/NGPC"
    
